-- CreateTable
CREATE TABLE `Admin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `username` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NULL,
    `lastName` VARCHAR(191) NULL,
    `bio` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,

    UNIQUE INDEX `Admin_email_key`(`email`),
    UNIQUE INDEX `Admin_username_key`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Response` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email_address` VARCHAR(191) NOT NULL,
    `applicant_name` VARCHAR(191) NOT NULL,
    `applicant_company_name` VARCHAR(191) NOT NULL,
    `company_address` VARCHAR(191) NOT NULL,
    `telephone_number` VARCHAR(191) NOT NULL,
    `revenue_sources` VARCHAR(191) NOT NULL,
    `diversification` VARCHAR(191) NOT NULL,
    `financial_strategy` VARCHAR(191) NOT NULL,
    `budget_management` VARCHAR(191) NOT NULL,
    `financial_reporting` VARCHAR(191) NOT NULL,
    `grant_acquisition` VARCHAR(191) NOT NULL,
    `investor_attraction` VARCHAR(191) NOT NULL,
    `reserves_and_continuity` VARCHAR(191) NOT NULL,
    `sustainability_plan` VARCHAR(191) NOT NULL,
    `clear_vision_and_mission` VARCHAR(191) NOT NULL,
    `defined_strategic_goals` VARCHAR(191) NOT NULL,
    `alignment_with_market_trends` VARCHAR(191) NOT NULL,
    `innovation_driven_strategy` VARCHAR(191) NOT NULL,
    `implementation_plan_and_execution` VARCHAR(191) NOT NULL,
    `resource_allocation` VARCHAR(191) NOT NULL,
    `monitoring_and_control_mechanisms` VARCHAR(191) NOT NULL,
    `responsiveness_to_changes` VARCHAR(191) NOT NULL,
    `regular_review_and_update_of_strategy` VARCHAR(191) NOT NULL,
    `performance_against_strategic_goals` VARCHAR(191) NOT NULL,
    `use_of_feedback_in_strategic_revision` VARCHAR(191) NOT NULL,
    `stakeholder_identification` VARCHAR(191) NOT NULL,
    `stakeholder_engagement_in_strategy` VARCHAR(191) NOT NULL,
    `responsiveness_to_stakeholder_feedback` VARCHAR(191) NOT NULL,
    `clarity_of_leadership_roles` VARCHAR(191) NOT NULL,
    `effective_of_leadership` VARCHAR(191) NOT NULL,
    `transparency_and_accountability_in_governance` VARCHAR(191) NOT NULL,
    `inclusiveness_in_decisionmaking_process` VARCHAR(191) NOT NULL,
    `staff_motivation_and_morale` VARCHAR(191) NOT NULL,
    `staff_competence` VARCHAR(191) NOT NULL,
    `clear_job_description_and_role_expectatons` VARCHAR(191) NOT NULL,
    `ongoing_training_and_development` VARCHAR(191) NOT NULL,
    `efficiency_operations` VARCHAR(191) NOT NULL,
    `quality_control_system` VARCHAR(191) NOT NULL,
    `technology_use` VARCHAR(191) NOT NULL,
    `risk_management` VARCHAR(191) NOT NULL,
    `performance_evaluation` VARCHAR(191) NOT NULL,
    `performance_feedback` VARCHAR(191) NOT NULL,
    `reward_recognition` VARCHAR(191) NOT NULL,
    `services_offered` VARCHAR(191) NOT NULL,
    `service_relevance` VARCHAR(191) NOT NULL,
    `service_innovativeness` VARCHAR(191) NOT NULL,
    `service_quality` VARCHAR(191) NOT NULL,
    `service_timeliness` VARCHAR(191) NOT NULL,
    `service_responsiveness` VARCHAR(191) NOT NULL,
    `service_accessibility` VARCHAR(191) NOT NULL,
    `technology_service_delivery` VARCHAR(191) NOT NULL,
    `service_impact` VARCHAR(191) NOT NULL,
    `feedback_utilization` VARCHAR(191) NOT NULL,
    `service_review` VARCHAR(191) NOT NULL,
    `startups_supported` VARCHAR(191) NOT NULL,
    `job_creation` VARCHAR(191) NOT NULL,
    `revenue_growth` VARCHAR(191) NOT NULL,
    `novel_solutions` VARCHAR(191) NOT NULL,
    `patents_ips` VARCHAR(191) NOT NULL,
    `rd_initiatives` VARCHAR(191) NOT NULL,
    `local_economy_contribution` VARCHAR(191) NOT NULL,
    `community_engagement` VARCHAR(191) NOT NULL,
    `partnerships_collaborations` VARCHAR(191) NOT NULL,
    `startup_sustainability` VARCHAR(191) NOT NULL,
    `long_term_value_creation` VARCHAR(191) NOT NULL,
    `strategic_vision` VARCHAR(191) NOT NULL,
    `working_space` VARCHAR(191) NOT NULL,
    `comfort_ambiance` VARCHAR(191) NOT NULL,
    `accessibility_wheelchair` VARCHAR(191) NOT NULL,
    `safety_equipment` VARCHAR(191) NOT NULL,
    `internet_connection` VARCHAR(191) NOT NULL,
    `necessary_hardware` VARCHAR(191) NOT NULL,
    `software_tools_availability` VARCHAR(191) NOT NULL,
    `power_reliability` VARCHAR(191) NOT NULL,
    `security_measures` VARCHAR(191) NOT NULL,
    `meeting_rooms` VARCHAR(191) NOT NULL,
    `event_space` VARCHAR(191) NOT NULL,
    `av_equipment_quality` VARCHAR(191) NOT NULL,
    `kitchen_facilities` VARCHAR(191) NOT NULL,
    `relaxation_recreation` VARCHAR(191) NOT NULL,
    `cleanliness_maintenance` VARCHAR(191) NOT NULL,
    `fulltime_staff` VARCHAR(191) NOT NULL,
    `staff_qualifications` VARCHAR(191) NOT NULL,
    `staff_turnover` VARCHAR(191) NOT NULL,
    `staff_training` VARCHAR(191) NOT NULL,
    `local_partners` VARCHAR(191) NOT NULL,
    `local_partnership_quality` VARCHAR(191) NOT NULL,
    `collaboration_outcome` VARCHAR(191) NOT NULL,
    `intl_partners` VARCHAR(191) NOT NULL,
    `intl_partners_quality` VARCHAR(191) NOT NULL,
    `intl_collaboration_outcome` VARCHAR(191) NOT NULL,
    `network_participation` VARCHAR(191) NOT NULL,
    `international_network_participation` VARCHAR(191) NOT NULL,
    `network_benefits` VARCHAR(191) NOT NULL,
    `alumni_network` VARCHAR(191) NOT NULL,
    `alumni_engagement` VARCHAR(191) NOT NULL,
    `alumni_success_stories` VARCHAR(191) NOT NULL,
    `governance_structure` VARCHAR(191) NOT NULL,
    `roles_responsibilities` VARCHAR(191) NOT NULL,
    `decision_making` VARCHAR(191) NOT NULL,
    `diversity_representation` VARCHAR(191) NOT NULL,
    `existence_clarity_policies` VARCHAR(191) NOT NULL,
    `alignment_legal_ethical_policies` VARCHAR(191) NOT NULL,
    `effectiveness_policies_operations` VARCHAR(191) NOT NULL,
    `review_update_policies` VARCHAR(191) NOT NULL,
    `compliance_legal_requirements` VARCHAR(191) NOT NULL,
    `risk_management_strategies` VARCHAR(191) NOT NULL,
    `risk_management_effectiveness` VARCHAR(191) NOT NULL,
    `legal_compliance_history` VARCHAR(191) NOT NULL,
    `stakeholder_engagement` VARCHAR(191) NOT NULL,
    `transparency_stakeholders` VARCHAR(191) NOT NULL,
    `responsiveness_feedback` VARCHAR(191) NOT NULL,
    `curriculum_entrepreneurship` VARCHAR(191) NOT NULL,
    `curriculum_comprehensiveness` VARCHAR(191) NOT NULL,
    `curriculum_alignment` VARCHAR(191) NOT NULL,
    `curriculum_innovation` VARCHAR(191) NOT NULL,
    `quality_of_trainers` VARCHAR(191) NOT NULL,
    `experiential_learning` VARCHAR(191) NOT NULL,
    `digital_tools_platforms` VARCHAR(191) NOT NULL,
    `learner_engagement` VARCHAR(191) NOT NULL,
    `assessment_techniques` VARCHAR(191) NOT NULL,
    `feedback_quality` VARCHAR(191) NOT NULL,
    `curriculum_effectiveness` VARCHAR(191) NOT NULL,
    `alumni_successes` VARCHAR(191) NOT NULL,
    `industry_feedback` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
